In [97]:
import pandas as pd

In [98]:
df=pd.read_csv("housing.csv")

In [99]:
print(df.shape)

(20640, 10)


In [100]:
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  


In [101]:
X=df.drop("median_house_value",axis=1)

In [102]:
Y=df["median_house_value"]

In [103]:
print(X.shape)

(20640, 9)


In [104]:
print(Y.shape)

(20640,)


In [105]:
print(X.isnull().sum())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64


In [106]:
print(Y.isnull().sum())

0


In [107]:
print(X.info())

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  str    
dtypes: float64(8), str(1)
memory usage: 1.6 MB
None


In [108]:
print(X.describe())

          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  
count    20433.000000  20640.000000  20640.000000   20640.000000  
mean       537.870553   1425.476744    499.539680       3.870671  
std        421.385070   1132.462122    382.329753       1.899822  
min          1.000000      3.000000      1.000000       0.499900  
25%        296.000000    

In [109]:
print(X["ocean_proximity"].unique())

<ArrowStringArray>
['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND']
Length: 5, dtype: str


In [110]:
from sklearn.model_selection import train_test_split

In [111]:
X_train,X_test,Y_train,Y_test=train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=78
)

In [112]:
print(X_train)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7896     -118.07     33.86                17.0       3666.0           562.0   
3531     -118.54     34.27                28.0       2309.0           300.0   
751      -122.07     37.67                27.0       3239.0           671.0   
5830     -118.31     34.20                36.0       1692.0           263.0   
6096     -117.87     34.12                34.0       1004.0           220.0   
...          ...       ...                 ...          ...             ...   
6454     -118.06     34.12                34.0       2941.0           558.0   
4136     -118.18     34.12                52.0       1081.0           311.0   
6039     -117.73     34.07                33.0       1025.0           261.0   
16854    -122.42     37.62                36.0       1017.0           165.0   
6853     -118.16     34.07                42.0       3836.0           777.0   

       population  households  median_income ocean_

In [113]:
from sklearn.impute import SimpleImputer

In [114]:
imputer=SimpleImputer(strategy="median")

In [115]:
X_train[["total_bedrooms"]]=imputer.fit_transform(
    X_train[["total_bedrooms"]]
)
X_test[["total_bedrooms"]]=imputer.transform(
    X_test[["total_bedrooms"]]
)

In [116]:
print(X_train["total_bedrooms"].isnull().sum())

0


In [117]:
print(X_test["total_bedrooms"].isnull().sum())

0


In [118]:
print(imputer.statistics_)

[434.]


In [119]:
print(X_train.info())

<class 'pandas.DataFrame'>
Index: 16512 entries, 7896 to 6853
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16512 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
 8   ocean_proximity     16512 non-null  str    
dtypes: float64(8), str(1)
memory usage: 1.4 MB
None


In [120]:
print(X_train["ocean_proximity"].unique())

<ArrowStringArray>
['<1H OCEAN', 'NEAR BAY', 'NEAR OCEAN', 'INLAND', 'ISLAND']
Length: 5, dtype: str


In [121]:
from sklearn.preprocessing import OneHotEncoder

In [122]:
encoder=OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

In [123]:
ocean_train=encoder.fit_transform(
    X_train[["ocean_proximity"]]
)

In [124]:
print(ocean_train[:5])

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [125]:
ocean_test=encoder.transform(
    X_test[["ocean_proximity"]]
)

In [126]:
ocean_columns=encoder.get_feature_names_out(
    ["ocean_proximity"]
)
print(ocean_columns)

['ocean_proximity_<1H OCEAN' 'ocean_proximity_INLAND'
 'ocean_proximity_ISLAND' 'ocean_proximity_NEAR BAY'
 'ocean_proximity_NEAR OCEAN']


In [127]:
print(X_train.shape)
print(X_test.shape)

print(ocean_train.shape)
print(ocean_test.shape)

(16512, 9)
(4128, 9)
(16512, 5)
(4128, 5)


In [128]:
ocean_train_df = pd.DataFrame(
    ocean_train,
    columns=ocean_columns,
    index=X_train.index
)

ocean_test_df = pd.DataFrame(
    ocean_test,
    columns=ocean_columns,
    index=X_test.index
)

In [129]:
X_train=X_train.drop("ocean_proximity",axis=1)
X_test=X_test.drop("ocean_proximity",axis=1)

In [130]:
X_train=pd.concat(
    [X_train,ocean_train_df],axis=1
)
X_test=pd.concat(
    [X_test,ocean_test_df],axis=1
)

In [131]:
print(X_train.head())

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7896    -118.07     33.86                17.0       3666.0           562.0   
3531    -118.54     34.27                28.0       2309.0           300.0   
751     -122.07     37.67                27.0       3239.0           671.0   
5830    -118.31     34.20                36.0       1692.0           263.0   
6096    -117.87     34.12                34.0       1004.0           220.0   

      population  households  median_income  ocean_proximity_<1H OCEAN  \
7896      2104.0       579.0         5.6818                        1.0   
3531       931.0       302.0         6.7415                        1.0   
751       1469.0       616.0         3.2465                        0.0   
5830       778.0       278.0         5.0865                        1.0   
6096       772.0       217.0         3.8571                        1.0   

      ocean_proximity_INLAND  ocean_proximity_ISLAND  \
7896                     0.0  

In [132]:
from sklearn.preprocessing import StandardScaler

In [133]:
scaler=StandardScaler()

In [134]:
numeric_columns=[
    "longitude",
    "latitude",
    "housing_median_age",
    "total_rooms",
    "total_bedrooms",
    "population",
    "households",
    "median_income"
]

In [135]:
X_train[numeric_columns]=scaler.fit_transform(
    X_train[numeric_columns]
)

In [136]:
X_test[numeric_columns]=scaler.transform(
    X_test[numeric_columns]
)

In [137]:
print(X_train[numeric_columns].mean())

longitude             4.675631e-15
latitude             -2.144064e-15
housing_median_age    4.819573e-17
total_rooms           3.872871e-18
total_bedrooms        4.475318e-17
population            3.442552e-17
households           -1.506117e-17
median_income         1.790127e-16
dtype: float64


In [138]:
print(X_train[numeric_columns].std())

longitude             1.00003
latitude              1.00003
housing_median_age    1.00003
total_rooms           1.00003
total_bedrooms        1.00003
population            1.00003
households            1.00003
median_income         1.00003
dtype: float64


In [139]:
from sklearn.linear_model import LinearRegression

In [140]:
model=LinearRegression()

In [142]:
model.fit(X_train,Y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](13,)","[-53148.57,-53895.5 , 13046.51,..., 87919.77,-16080.66, -7490.11]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](13,)","['longitude','latitude','housing_median_age',...,'ocean_proximity_ISLAND', 'ocean_proximity_NEAR BAY','ocean_proximity_NEAR OCEAN']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,2.316e+05
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,13
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(12)


In [143]:
print(model.intercept_)

231621.4368659555


In [144]:
print(model.coef_)

[-53148.56614448 -53895.49667049  13046.51237366  -9710.91707029
  31663.58226531 -44911.44570717  27662.29987464  73678.69468723
 -12489.37762788 -51859.61486636  87919.76860222 -16080.66365525
  -7490.11245273]


In [145]:
predictions=model.predict(X_test)

In [146]:
print(predictions[:10])

[190728.69039616 107735.98690893 208541.7725608  126513.74607533
  85677.32699084 192712.95049228 528979.85657622 211507.60384405
 212956.79059195  75384.79848014]


In [148]:
print(Y_test.iloc[:10].values)

[169400. 103400. 194800.  97300. 156800. 222400. 500001. 291700. 160700.
  65900.]


In [152]:
comparision=pd.DataFrame({
    "Acutal":Y_test.values,
    "Predicted":predictions
})
print(comparision.head(10))

     Acutal      Predicted
0  169400.0  190728.690396
1  103400.0  107735.986909
2  194800.0  208541.772561
3   97300.0  126513.746075
4  156800.0   85677.326991
5  222400.0  192712.950492
6  500001.0  528979.856576
7  291700.0  211507.603844
8  160700.0  212956.790592
9   65900.0   75384.798480


In [154]:
comparision["Error"]=(
    comparision["Acutal"]-comparision["Predicted"]
)
print(comparision.head(10))

     Acutal      Predicted         Error
0  169400.0  190728.690396 -21328.690396
1  103400.0  107735.986909  -4335.986909
2  194800.0  208541.772561 -13741.772561
3   97300.0  126513.746075 -29213.746075
4  156800.0   85677.326991  71122.673009
5  222400.0  192712.950492  29687.049508
6  500001.0  528979.856576 -28978.856576
7  291700.0  211507.603844  80192.396156
8  160700.0  212956.790592 -52256.790592
9   65900.0   75384.798480  -9484.798480


In [157]:
from sklearn.metrics import mean_absolute_error

In [158]:
mae=mean_absolute_error(
    Y_test,
    predictions
)

In [159]:
print("MAE:",mae)

MAE: 49682.80001746253


In [160]:
from sklearn.metrics import mean_squared_error

In [162]:
mse=mean_squared_error(
    Y_test,
    predictions
)
print("MSE:",mse)

MSE: 4603237080.648536


In [163]:
import numpy as np

In [173]:
rmse=np.sqrt(mse)

In [174]:
print("RMSE:",rmse)

RMSE: 67847.15970951573


In [175]:
from sklearn.metrics import r2_score

In [176]:
r2=r2_score(
    Y_test,
    predictions
)
print("R^2:",r2)

R^2: 0.6510348972472126


In [177]:
import numpy as np

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)


mae = mean_absolute_error(
    Y_test,
    predictions
)

mse = mean_squared_error(
    Y_test,
    predictions
)

rmse = np.sqrt(mse)

r2 = r2_score(
    Y_test,
    predictions
)


print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 49682.80001746253
MSE: 4603237080.648536
RMSE: 67847.15970951573
R²: 0.6510348972472126


In [178]:
#Generatlization:How well the model performs in the unseen data 

In [179]:
train_predictions=model.predict(X_train)

In [180]:
train_mse=mean_squared_error(
    Y_train,
    train_predictions
)

In [181]:
train_rmse=np.sqrt(train_mse)

In [184]:
test_predictions=model.predict(X_test)

In [186]:
test_mse=mean_squared_error(
        Y_test,
        test_predictions
)

In [187]:
test_rmse=np.square(test_mse)

In [188]:
print("Training RMSE:",train_mse)
print("Testing RMSE:",test_rmse)

Training RMSE: 4751928527.652079
Testing RMSE: 2.1189791620657656e+19


In [191]:
mae = mean_absolute_error(Y_test, predictions)
mse = mean_squared_error(Y_test, predictions)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, predictions)

In [192]:
print("Training RMSE:",train_mse)
print("Testing RMSE:",test_rmse)

Training RMSE: 4751928527.652079
Testing RMSE: 2.1189791620657656e+19
